export const AUTH = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
};

export const UI = {
  SHOW_LOADER: 'SHOW_LOADER',
  HIDE_LOADER: 'HIDE_LOADER'
};

export const CONTACTS = {
  SET_CONTACTS: 'SET_CONTACTS',
  RESET_CONTACTS: 'RESET_CONTACTS',
  ADD_CONTACT: 'ADD_CONTACT',
  EDIT_CONTACT: 'EDIT_CONTACT',
  REMOVE_CONTACT: 'REMOVE_CONTACT'
};

export const CONTACT = {
  SET_CONTACT: 'SET_CONTACT',
  RESET_CONTACT: 'RESET_CONTACT'
};

export const SEARCH = {
  SET_SEARCH_CONTACT: 'SET_SEARCH_CONTACT',
  RESET_SEARCH: 'RESET_SEARCH'
};
